// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwtwslsweswgeekxakme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3dHdzbHN3ZXN3Z2Vla3hha21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzczMjIsImV4cCI6MjA2NzU1MzMyMn0.Zbi6bnk_12ANLf2LZRPBacEOmT-KB6KRB5ZOpo_KlOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});